kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
nodes:
  - role: control-plane
  - role: worker
    labels:
      app: backend

  - role: worker
    labels:
      app: frontend

  - role: worker
    labels:
      app: backend

  - role: worker
    labels:
      app: frontend

  - role: worker
    labels:
      app: db

  - role: worker
    labels:
      app: db
